version: '2'
services:
  elasticsearch:
    image: 'elasticsearch:7.3.2'
    volumes:
      - 'skd_esdata_geoshape:/usr/share/elasticsearch/data'
    environment:
      discovery.type: single-node
  kibana:
    image: 'kibana:7.3.2'
    ports:
      - '127.0.0.1:5601:5601'
    depends_on:
      - elasticsearch
  dump:
    image: taskrabbit/elasticsearch-dump
    volumes:
      - './dump:/data'
      - './dump.sh:/dump.sh'
    entrypoint: 'sh dump.sh'
    depends_on:
      - elasticsearch
volumes:
  skd_esdata_geoshape:
    driver: local
