version: '2'
services:
  elasticsearch:
    image: 'elasticsearch:7.3.2'
    volumes:
      - 'skd_esdata_work_entries:/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
  kibana:
    image: 'kibana:7.3.2'
    ports:
      - '127.0.0.1:5601:5601'
    depends_on:
      - elasticsearch
  logstash:
    image: 'logstash:7.3.2'
    volumes:
      - './logstash.conf:/conf/logstash.conf'
      - './work_entries.csv:/work_entries.csv:ro'
    command: '-f /conf/logstash.conf'
    depends_on:
      - elasticsearch
volumes:
  skd_esdata_work_entries:
    driver: local
